version: '3.8'

services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - 27017:27017 # MongoDB
      - 7474:7474   # Neo4j (HTTP)
      - 7687:7687   # Neo4j (Bolt)
      - 6379:6379   # Redis

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "neo4j/test"

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: