version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - dbs_network
    environment:
      - MONGO_DB_NAME=library
      - MONGO_PORT=27017
      - MONGO_HOST=mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - dbs_network

  neo4j:
    image: neo4j
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./../Data:/import
    command: ["neo4j"]
    networks:
      - dbs_network

volumes:
  mongodb_data:
  neo4j_data:

networks:
  dbs_network:
    driver: bridge